import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "OMS FILE UPLOAD",
  description: "Generated by Johannes Mathelele",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        {children}
      </body>
    </html>
  );
}


//className={`${geistSans.variable} ${geistMono.variable} antialiased`}